// CICLO FOR 

//Objetos  de 0 a 4
let Lenguajes = ["Linux","Python","Java","JavaScript","SQL"]

                //FUNCION DEL FOR

//1) creamos una variable dentro del for con su valor
//2) Ponemos punto para cerrar ese espacio
//3) luego del  punto y coma ponemos la condicion
//4) siempre cerrar una condicion o  variable con el punto y coma


// si idioms que vale 0 es menor que lenguajes que vale 4 (por la cantidad de objetos que tiene)
// entonces sumar hasta la cantidad de objetos que hay y si se llega a esa cantidad no seguir sumando
for(let idioms = 0 ; idioms < Lenguajes.length; idioms++){
    console.log(Lenguajes[idioms]);
}

