console.log({"username": "ryan", "scores" : 80});
// Objeto donde podemos tipos de datos en  la consola







let Prueba1 = "23";
let Prueba2 = "23";

let result = Prueba1 == Prueba2;

//console.log(result)

if (result == true ){
    console.log("Es mayor que el numero ingresado")
}else if (result == false){
    console.log("No es mayor que la variable ingresada")
}else{
    console.log("En este caso son iguales")
}

