// Variables

var NombreUser = "santiago";
let lastname = "Ceron ";


// para cambiar el valor de la variable
NombreUser = "Luis";
lastname = "Martinez"

// las unicos signos que js soporta en el nombre de una variable es
$Variable = "prueba";
_VariAble = "Prueba2";



// Constante
const PI = 3.134;


// Llamar una variable o constante
console.log(PI, NombreUser, lastname)


// CamelCase es como se escribe al poner iniciales mayusculas como la joroba de un camello
let UserName = "lmartinez";

console.log(UserName);

// var es para asignar una variable
// let igualmente para crear una variable pero no se puede reasignar
// const para asignar constantes se mantiene no se puede cambiar el valor



