// OPERADORES
let numerouno = 30;
let numerodos = 10;

// Para dar un espacio al resultado de la variable
let resultado = numerouno + " " + numerodos ;

console.log(resultado);


// 2
//Concatenacion unir dos string o  cadenas

let Nombre  = "Santi"
let Apellido = "Ceron"

let NombreCompleto = Nombre + Apellido;

console.log(NombreCompleto)

// 3 Comparacion para saber que resultado es mayo o menor o igual
// asi comparando nuestros datos 
// saldra false o true dependiendo de el resultado

let NumberOne = "100"
let NumberTwo = "300"

let comparacion = NumberOne > NumberTwo

console.log(comparacion)



//4 comparando si es el mismo resultado que esta en la variable de la otra variable

let ContraseñaDB = "JoE"

let contraseña = "joe"

let result = contraseña == ContraseñaDB

console.log(result)


//5) Diferencia
let Num1 = 100;
let Num2 = 100;

// Se pone el signo y el igual para hacer una diferencia
let resul = num1 != Num2
// es num1 diferente a numero2?
console.log(resul)

// false no son diferentes
// true si son diferentes



