// BUCLES JAVA SCRIPT
// 1) WHILE

// ASIGNAMOS LA VARIABLE
let iter = 50;

// MIENTRAS QUE LA VARIABLE SEA MAYOR CERO
while(iter > 0){
    // ME VAS A IMPRIMIR EL RESULTADO
    console.log(iter)
    // DE ESTA VARIABLE CON SU RESULTADO VAS A RESTARLE
    // HASTA QUE NO SEA MAYOR A CERO
    iter = iter - 1;
}

// PRACTICA 2

let bucle = 20;

while(bucle > 10 ){
    console.log(bucle)

    bucle = bucle -1
} 


let bug = 10;

while (bug  > 10 ){
    console.log(bug)
     bug++
}